services:
  requisiciones:
    build: .
    container_name: requisiciones
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file: .env
    environment:
      - TZ=America/El_Salvador
    networks:
      - proxy

networks:
  proxy:
    external: true
